### ISSUE TITLE
--iron-icon-width wrong

### ISSUE THREAD

**Issue by davidsteinberger** [predixdesignsystem/px-datetime-common#23]
## Expected behavior and actual behavior:

*calculateRem()* should calculate correct *rem*-value.

## Steps to reproduce the problem:

check transpiled style-module's `--iron-icon-width` in [repo](https://github.com/predixdesignsystem/px-datetime-common/blob/master/css/px-datetime-entry-styles.html).

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

px-datetime-common@3.2.2

I may be wrong but I think you're missing an import of *_settings.defaults.scss*

**Comment by evanjd** [comment]
Thanks, I'll get right on it today.

**Comment by evanjd** [comment]
[v3.2.3](https://github.com/predixdesignsystem/px-datetime-common/releases/tag/v3.2.3) has been released that resolves this regression. Thanks for raising the issue! 👍
