### ISSUE TITLE
Load moment locales.min.js to support switching locale

### ISSUE THREAD

**Issue by manderson23** [predixdesignsystem/px-datetime-common#4]
I'd like to use locale en-gb with Px.moment.

To support this I had to load `<script type="text/javascript" src="../pxmoment/min/locales.min.js"></script>` in `px-datetime-imports-deep.html`

**Comment by benoitjchevalier** [comment]
Hello,

In what context did you need this? In general we handle locale by passing down a "timeZone" or similar property on the components using time/date and then use [moment timezone](http://momentjs.com/timezone/) with this "timeZone" string

**Comment by manderson23** [comment]
I'm specifying a date format with pattern `L` when using `px-vis-timeseries`.

Since `L` uses the locale of the moment instance I need to change the locale on `Px.moment` since that is what `px-vis-timeseries` uses.

**Comment by nonmetalhail** [comment]
Not answering your direct question, but...

px-vis-timeseries only uses Moment in certain places, namely within the Register/Tooltip and the tooltip on Events. The axes do NOT use Moment, preferring d3's axis constructor. So if you succeed in changing the locale, you will still have an issue keeping the axes in sync.

**Comment by manderson23** [comment]
I'm not as concerned about axes since I'm unlikely to be using day, month, year combination there.

The different order of day and month between US and GB is my main issue at the moment hence I wanted to user the locale format.
